import type { Metadata } from "next";
import { fetchQuery } from "convex/nextjs";
import { api } from "@convex/_generated/api";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n/config";
import { descriptionFrom, publicMetadata } from "../_metadata";

export const dynamic = "force-dynamic";
export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; const content = await fetchQuery(api.publicSite.public.getContentBlock, { key: "contact", locale }); const bn = locale === "bn"; return publicMetadata({ locale, path: "/contact", title: content?.title.value || (bn ? "যোগাযোগ" : "Contact"), description: descriptionFrom(content?.body.value ?? "", bn ? "ধ্রুবক কোচিং সেন্টারের ঠিকানা, ফোন ও ইমেইল দেখুন।" : "Find the address, phone number, and email for Dhrubok Coaching Centre.") }); }
export default async function ContactPage({ params }: { params: Promise<{ locale: string }> }) { const { locale } = await params; if (!isLocale(locale)) notFound(); const [content, settings] = await Promise.all([fetchQuery(api.publicSite.public.getContentBlock, { key: "contact", locale }), fetchQuery(api.settings.getPublic, {})]); const bn = locale === "bn"; const address = settings ? (bn ? settings.addressBn : settings.addressEn) : ""; const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`; return <section className="section container narrow"><p className="eyebrow">{bn ? "যোগাযোগ" : "Contact"}</p><h1>{content?.title.value || (bn ? "আমাদের সাথে যোগাযোগ করুন" : "Contact us")}</h1><p className="lead-copy">{content?.body.value || (bn ? "ভর্তি ও কোর্স সম্পর্কে জানতে ফোন বা ইমেইল করুন।" : "Call or email us to learn about admission and courses.")}</p>{settings ? <dl className="contact-list"><div><dt>{bn ? "ঠিকানা" : "Address"}</dt><dd>{address}</dd></div><div><dt>{bn ? "ফোন" : "Phone"}</dt><dd><a href={`tel:+${settings.phone}`}>+{settings.phone}</a></dd></div><div><dt>{bn ? "ইমেইল" : "Email"}</dt><dd><a href={`mailto:${settings.email}`}>{settings.email}</a></dd></div></dl> : <p className="empty-panel">{bn ? "যোগাযোগের তথ্য এখনো প্রকাশিত হয়নি।" : "Contact details have not been published yet."}</p>}{address && <a className="button button-secondary" href={mapUrl} target="_blank" rel="noreferrer">{bn ? "মানচিত্রে দেখুন" : "Open in maps"}</a>}</section>; }
