import { paginationOptsValidator } from "convex/server";
import { v } from "convex/values";
import { mutation, query } from "../_generated/server";
import { requireOwner } from "../model/auth";
import { writeAudit } from "../model/audit";
import { assignmentDoc, assertDateRange, mustGet, paginationResult } from "./shared";

export const listForBatch = query({ args: { batchId: v.id("batches"), status: v.union(v.literal("active"), v.literal("ended")), paginationOpts: paginationOptsValidator }, returns: paginationResult(assignmentDoc), handler: async (ctx, args) => { await requireOwner(ctx); return await ctx.db.query("teacherBatchAssignments").withIndex("by_batchId_and_status", q => q.eq("batchId", args.batchId).eq("status", args.status)).paginate(args.paginationOpts); } });

export const create = mutation({ args: { teacherId: v.id("teachers"), batchId: v.id("batches"), subjectId: v.optional(v.id("subjects")), startsOn: v.string(), endsOn: v.optional(v.string()) }, returns: v.id("teacherBatchAssignments"), handler: async (ctx, args) => {
  const { account } = await requireOwner(ctx); assertDateRange(args.startsOn, args.endsOn); const teacher = await mustGet(ctx, "teachers", args.teacherId, "Teacher"); const batch = await mustGet(ctx, "batches", args.batchId, "Batch");
  if (teacher.status !== "active") throw new Error("Only active teachers may receive assignments"); if (batch.status === "archived" || batch.status === "completed") throw new Error("Archived or completed batches cannot receive active assignments");
  if (args.subjectId) { const subject = await mustGet(ctx, "subjects", args.subjectId, "Subject"); if (subject.status !== "active") throw new Error("Archived subjects cannot receive active assignments"); const link = await ctx.db.query("courseSubjects").withIndex("by_courseId_and_subjectId", q => q.eq("courseId", batch.courseId).eq("subjectId", args.subjectId!)).unique(); if (!link) throw new Error("Subject is not linked to the batch course"); }
  const existing = await ctx.db.query("teacherBatchAssignments").withIndex("by_teacherId_and_batchId", q => q.eq("teacherId", args.teacherId).eq("batchId", args.batchId)).take(100); if (existing.some(item => item.status === "active" && item.subjectId === args.subjectId)) throw new Error("Active teacher assignment already exists");
  const id = await ctx.db.insert("teacherBatchAssignments", { ...args, status: "active", createdAt: Date.now(), createdByAccountId: account._id }); await writeAudit(ctx, { actorAccountId: account._id, actorRole: "owner", action: "teacher_batch_assignment.created", entityType: "teacherBatchAssignment", entityId: id, summary: "Teacher assigned to batch" }); return id;
} });

export const end = mutation({ args: { assignmentId: v.id("teacherBatchAssignments"), endsOn: v.string() }, returns: v.null(), handler: async (ctx, args) => { const { account } = await requireOwner(ctx); const assignment = await mustGet(ctx, "teacherBatchAssignments", args.assignmentId, "Assignment"); if (assignment.status === "ended") return null; assertDateRange(assignment.startsOn, args.endsOn); const schedules = await ctx.db.query("batchSchedules").withIndex("by_teacherId_and_status", q => q.eq("teacherId", assignment.teacherId).eq("status", "active")).take(200); if (schedules.some(item => item.batchId === assignment.batchId && item.subjectId === assignment.subjectId)) throw new Error("Cancel active schedules before ending this assignment"); await ctx.db.patch("teacherBatchAssignments", args.assignmentId, { status: "ended", endsOn: args.endsOn }); await writeAudit(ctx, { actorAccountId: account._id, actorRole: "owner", action: "teacher_batch_assignment.ended", entityType: "teacherBatchAssignment", entityId: args.assignmentId, summary: "Teacher batch assignment ended" }); return null; } });
