import { paginationOptsValidator } from "convex/server";
import { v } from "convex/values";
import { mutation, query } from "../_generated/server";
import { requireOwner } from "../model/auth";
import { writeAudit } from "../model/audit";
import { academicStatus, assertIsoDate, batchDoc, cleanRequired, mustGet, normalizeCode, normalizeSlug, paginationResult } from "./shared";
import { scheduleCourseSnapshot } from "./snapshotHooks";

const fields = {
  courseId: v.id("courses"), code: v.string(), slug: v.string(), nameBn: v.string(), nameEn: v.string(),
  startDate: v.string(), status: academicStatus, admissionOpen: v.boolean(), isPublic: v.boolean(), publicSortOrder: v.number(),
};

async function validate(ctx: Parameters<typeof mustGet>[0], args: { courseId: never; status: string; startDate: string; admissionOpen: boolean; isPublic: boolean }) {
  const course = await mustGet(ctx, "courses", args.courseId, "Course");
  if (course.status === "archived") throw new Error("Archived courses cannot receive batches");
  assertIsoDate(args.startDate, "Batch start date");
  if ((args.admissionOpen || args.isPublic) && args.status !== "active") throw new Error("Only active batches may be public or open for admission");
}

export const list = query({ args: { courseId: v.id("courses"), status: academicStatus, paginationOpts: paginationOptsValidator }, returns: paginationResult(batchDoc), handler: async (ctx, args) => { await requireOwner(ctx); return await ctx.db.query("batches").withIndex("by_courseId_and_status", q => q.eq("courseId", args.courseId).eq("status", args.status)).paginate(args.paginationOpts); } });
export const get = query({ args: { batchId: v.id("batches") }, returns: batchDoc, handler: async (ctx, args) => { await requireOwner(ctx); return await mustGet(ctx, "batches", args.batchId, "Batch"); } });
export const create = mutation({ args: fields, returns: v.id("batches"), handler: async (ctx, args) => { const { account } = await requireOwner(ctx); await validate(ctx, args as never); const code = normalizeCode(args.code); const slug = normalizeSlug(args.slug); if (await ctx.db.query("batches").withIndex("by_code", q => q.eq("code", code)).unique()) throw new Error("Batch code already exists"); if (await ctx.db.query("batches").withIndex("by_slug", q => q.eq("slug", slug)).unique()) throw new Error("Batch slug already exists"); const now = Date.now(); const id = await ctx.db.insert("batches", { ...args, code, slug, nameBn: cleanRequired(args.nameBn, "Bangla name"), nameEn: cleanRequired(args.nameEn, "English name"), createdAt: now, updatedAt: now }); await writeAudit(ctx, { actorAccountId: account._id, actorRole: "owner", action: "batch.created", entityType: "batch", entityId: id, summary: "Batch created" }); await scheduleCourseSnapshot(ctx, args.courseId); return id; } });
export const update = mutation({ args: { batchId: v.id("batches"), ...fields }, returns: v.null(), handler: async (ctx, args) => { await requireOwner(ctx); const current = await mustGet(ctx, "batches", args.batchId, "Batch"); if (current.status === "archived") throw new Error("Archived batches cannot be edited"); await validate(ctx, args as never); const code = normalizeCode(args.code); const slug = normalizeSlug(args.slug); const byCode = await ctx.db.query("batches").withIndex("by_code", q => q.eq("code", code)).unique(); const bySlug = await ctx.db.query("batches").withIndex("by_slug", q => q.eq("slug", slug)).unique(); if (byCode && byCode._id !== args.batchId) throw new Error("Batch code already exists"); if (bySlug && bySlug._id !== args.batchId) throw new Error("Batch slug already exists"); const { batchId, ...patch } = args; await ctx.db.patch("batches", batchId, { ...patch, roomBn: undefined, roomEn: undefined, code, slug, nameBn: cleanRequired(args.nameBn, "Bangla name"), nameEn: cleanRequired(args.nameEn, "English name"), updatedAt: Date.now() }); await scheduleCourseSnapshot(ctx, current.courseId); return null; } });
export const transition = mutation({ args: { batchId: v.id("batches"), status: v.union(v.literal("planned"), v.literal("active"), v.literal("completed")) }, returns: v.null(), handler: async (ctx, args) => { await requireOwner(ctx); const batch = await mustGet(ctx, "batches", args.batchId, "Batch"); if (batch.status === "archived") throw new Error("Archived batches cannot change lifecycle"); if (args.status === "planned" && batch.status !== "planned") throw new Error("A batch cannot return to planned status"); if (args.status === "active" && batch.status !== "planned") throw new Error("Only planned batches can be activated"); if (args.status === "completed" && batch.status !== "active") throw new Error("Only active batches can be completed"); await ctx.db.patch("batches", batch._id, { status: args.status, admissionOpen: args.status === "active" ? batch.admissionOpen : false, isPublic: args.status === "active" ? batch.isPublic : false, updatedAt: Date.now() }); await scheduleCourseSnapshot(ctx, batch.courseId); return null; } });
export const archive = mutation({ args: { batchId: v.id("batches") }, returns: v.null(), handler: async (ctx, args) => { const { account } = await requireOwner(ctx); const batch = await mustGet(ctx, "batches", args.batchId, "Batch"); if (batch.status === "archived") return null; const assignments = await ctx.db.query("teacherBatchAssignments").withIndex("by_batchId_and_status", q => q.eq("batchId", args.batchId).eq("status", "active")).take(1); const schedules = await ctx.db.query("batchSchedules").withIndex("by_batchId_and_status", q => q.eq("batchId", args.batchId).eq("status", "active")).take(1); const enrolments = await ctx.db.query("enrolments").withIndex("by_batchId_and_status", q => q.eq("batchId", args.batchId).eq("status", "active")).take(1); if (assignments.length || schedules.length || enrolments.length) throw new Error("Batch with active assignments, schedules, or enrolments cannot be archived"); await ctx.db.patch("batches", args.batchId, { status: "archived", admissionOpen: false, isPublic: false, updatedAt: Date.now() }); await writeAudit(ctx, { actorAccountId: account._id, actorRole: "owner", action: "batch.archived", entityType: "batch", entityId: args.batchId, summary: "Batch archived" }); await scheduleCourseSnapshot(ctx, batch.courseId); return null; } });
