import { v } from "convex/values";
import { query } from "../_generated/server";
import { requireStudent, requireTeacher } from "../model/auth";

const assignedBatchProjection = v.object({ batchId: v.id("batches"), code: v.string(), nameBn: v.string(), nameEn: v.string(), courseId: v.id("courses"), courseNameBn: v.string(), courseNameEn: v.string(), subjectId: v.optional(v.id("subjects")), startsOn: v.string(), endsOn: v.optional(v.string()) });
const studentBatchProjection = v.object({ enrolmentId: v.id("enrolments"), batchId: v.id("batches"), batchCode: v.string(), batchNameBn: v.string(), batchNameEn: v.string(), courseId: v.id("courses"), courseNameBn: v.string(), courseNameEn: v.string() });
const routineProjection = v.object({ scheduleId: v.id("batchSchedules"), batchId: v.id("batches"), batchNameBn: v.string(), batchNameEn: v.string(), teacherId: v.id("teachers"), teacherName: v.string(), subjectId: v.optional(v.id("subjects")), weekday: v.number(), startMinutes: v.number(), endMinutes: v.number() });

export const teacherAssignedBatches = query({ args: {}, returns: v.array(assignedBatchProjection), handler: async (ctx) => { const { teacher } = await requireTeacher(ctx); const assignments = await ctx.db.query("teacherBatchAssignments").withIndex("by_teacherId_and_status", q => q.eq("teacherId", teacher._id).eq("status", "active")).take(200); const result = []; for (const assignment of assignments) { const batch = await ctx.db.get("batches", assignment.batchId); if (!batch || batch.status === "archived") continue; const course = await ctx.db.get("courses", batch.courseId); if (!course || course.status === "archived") continue; result.push({ batchId: batch._id, code: batch.code, nameBn: batch.nameBn, nameEn: batch.nameEn, courseId: course._id, courseNameBn: course.nameBn, courseNameEn: course.nameEn, subjectId: assignment.subjectId, startsOn: assignment.startsOn, endsOn: assignment.endsOn }); } return result; } });

export const teacherRoutine = query({ args: {}, returns: v.array(routineProjection), handler: async (ctx) => { const { teacher } = await requireTeacher(ctx); const schedules = await ctx.db.query("batchSchedules").withIndex("by_teacherId_and_status", q => q.eq("teacherId", teacher._id).eq("status", "active")).take(200); const result = []; for (const schedule of schedules) { const batch = await ctx.db.get("batches", schedule.batchId); if (batch && batch.status !== "archived") result.push({ scheduleId: schedule._id, batchId: batch._id, batchNameBn: batch.nameBn, batchNameEn: batch.nameEn, teacherId: teacher._id, teacherName: teacher.displayName, subjectId: schedule.subjectId, weekday: schedule.weekday, startMinutes: schedule.startMinutes, endMinutes: schedule.endMinutes }); } return result; } });

export const studentEnrolments = query({ args: {}, returns: v.array(studentBatchProjection), handler: async (ctx) => { const { student } = await requireStudent(ctx); const enrolments = await ctx.db.query("enrolments").withIndex("by_studentId_and_status", q => q.eq("studentId", student._id).eq("status", "active")).take(100); const result = []; for (const enrolment of enrolments) { const batch = await ctx.db.get("batches", enrolment.batchId); const course = await ctx.db.get("courses", enrolment.courseId); if (batch && course && batch.status !== "archived" && course.status !== "archived") result.push({ enrolmentId: enrolment._id, batchId: batch._id, batchCode: batch.code, batchNameBn: batch.nameBn, batchNameEn: batch.nameEn, courseId: course._id, courseNameBn: course.nameBn, courseNameEn: course.nameEn }); } return result; } });

export const studentRoutine = query({ args: {}, returns: v.array(routineProjection), handler: async (ctx) => { const { student } = await requireStudent(ctx); const enrolments = await ctx.db.query("enrolments").withIndex("by_studentId_and_status", q => q.eq("studentId", student._id).eq("status", "active")).take(100); const result = []; for (const enrolment of enrolments) { const schedules = await ctx.db.query("batchSchedules").withIndex("by_batchId_and_status", q => q.eq("batchId", enrolment.batchId).eq("status", "active")).take(100); const batch = await ctx.db.get("batches", enrolment.batchId); if (!batch || batch.status === "archived") continue; for (const schedule of schedules) { const teacher = await ctx.db.get("teachers", schedule.teacherId); if (teacher?.status === "active") result.push({ scheduleId: schedule._id, batchId: batch._id, batchNameBn: batch.nameBn, batchNameEn: batch.nameEn, teacherId: teacher._id, teacherName: teacher.displayName, subjectId: schedule.subjectId, weekday: schedule.weekday, startMinutes: schedule.startMinutes, endMinutes: schedule.endMinutes }); } } return result; } });

export const teacherProfile = query({
  args: {}, returns: v.object({ employeeCode: v.string(), displayName: v.string(), nameBn: v.union(v.string(), v.null()), nameEn: v.union(v.string(), v.null()), loginEmail: v.string(), phone: v.string(), bioBn: v.string(), bioEn: v.string(), qualificationsBn: v.string(), qualificationsEn: v.string(), status: v.string() }),
  handler: async (ctx) => { const { teacher } = await requireTeacher(ctx); return { employeeCode: teacher.employeeCode, displayName: teacher.displayName, nameBn: teacher.nameBn ?? null, nameEn: teacher.nameEn ?? null, loginEmail: teacher.loginEmail, phone: teacher.phone, bioBn: teacher.bioBn, bioEn: teacher.bioEn, qualificationsBn: teacher.qualificationsBn, qualificationsEn: teacher.qualificationsEn, status: teacher.status }; },
});
