import { paginationOptsValidator } from "convex/server";
import { v } from "convex/values";
import { mutation, query } from "../_generated/server";
import { requireOwner } from "../model/auth";
import { assertDateRange, mustGet, paginationResult, scheduleDoc } from "./shared";

const scheduleFields = { batchId: v.id("batches"), teacherId: v.id("teachers"), subjectId: v.optional(v.id("subjects")), weekday: v.number(), startMinutes: v.number(), endMinutes: v.number(), roomBn: v.optional(v.string()), roomEn: v.optional(v.string()), effectiveFrom: v.string(), effectiveUntil: v.optional(v.string()) };

function validateTime(args: { weekday: number; startMinutes: number; endMinutes: number; effectiveFrom: string; effectiveUntil?: string }) { if (!Number.isSafeInteger(args.weekday) || args.weekday < 0 || args.weekday > 6) throw new Error("Weekday must be 0-6, where 0 is Sunday"); if (!Number.isSafeInteger(args.startMinutes) || !Number.isSafeInteger(args.endMinutes) || args.startMinutes < 0 || args.endMinutes > 1440 || args.endMinutes <= args.startMinutes) throw new Error("Schedule minutes must form a valid range within one day"); assertDateRange(args.effectiveFrom, args.effectiveUntil); }

async function validateRelations(ctx: Parameters<typeof mustGet>[0], args: { batchId: never; teacherId: never; subjectId?: never }) { const batch = await mustGet(ctx, "batches", args.batchId, "Batch"); const teacher = await mustGet(ctx, "teachers", args.teacherId, "Teacher"); if (batch.status === "archived" || batch.status === "completed" || teacher.status !== "active") throw new Error("Archived, completed, or inactive records cannot receive schedules"); if (args.subjectId) { const subject = await mustGet(ctx, "subjects", args.subjectId, "Subject"); if (subject.status !== "active") throw new Error("Archived subjects cannot receive schedules"); } const assignments = await ctx.db.query("teacherBatchAssignments").withIndex("by_teacherId_and_batchId", q => q.eq("teacherId", args.teacherId).eq("batchId", args.batchId)).take(100); if (!assignments.some(a => a.status === "active" && a.subjectId === args.subjectId)) throw new Error("An active matching teacher-batch assignment is required"); }

async function rejectOverlap(ctx: Parameters<typeof mustGet>[0], args: { scheduleId?: string; batchId: never; teacherId: never; weekday: number; startMinutes: number; endMinutes: number; effectiveFrom: string; effectiveUntil?: string }) { const teacherRows = await ctx.db.query("batchSchedules").withIndex("by_teacherId_and_weekday_and_status", q => q.eq("teacherId", args.teacherId).eq("weekday", args.weekday).eq("status", "active")).take(200); const batchRows = await ctx.db.query("batchSchedules").withIndex("by_batchId_and_weekday_and_status", q => q.eq("batchId", args.batchId).eq("weekday", args.weekday).eq("status", "active")).take(200); if ([...teacherRows, ...batchRows].some(row => { const datesOverlap = !(args.effectiveUntil && args.effectiveUntil < row.effectiveFrom) && !(row.effectiveUntil && row.effectiveUntil < args.effectiveFrom); return row._id !== args.scheduleId && datesOverlap && args.startMinutes < row.endMinutes && args.endMinutes > row.startMinutes; })) throw new Error("Schedule overlaps an active teacher or batch schedule"); }

export const listForBatch = query({ args: { batchId: v.id("batches"), status: v.union(v.literal("active"), v.literal("cancelled")), paginationOpts: paginationOptsValidator }, returns: paginationResult(scheduleDoc), handler: async (ctx, args) => { await requireOwner(ctx); return await ctx.db.query("batchSchedules").withIndex("by_batchId_and_status", q => q.eq("batchId", args.batchId).eq("status", args.status)).paginate(args.paginationOpts); } });
export const create = mutation({ args: scheduleFields, returns: v.id("batchSchedules"), handler: async (ctx, args) => { await requireOwner(ctx); validateTime(args); await validateRelations(ctx, args as never); await rejectOverlap(ctx, args as never); const now = Date.now(); return await ctx.db.insert("batchSchedules", { ...args, status: "active", createdAt: now, updatedAt: now }); } });
export const update = mutation({ args: { scheduleId: v.id("batchSchedules"), ...scheduleFields }, returns: v.null(), handler: async (ctx, args) => { await requireOwner(ctx); const current = await mustGet(ctx, "batchSchedules", args.scheduleId, "Schedule"); if (current.status === "cancelled") throw new Error("Cancelled schedules cannot be edited"); validateTime(args); await validateRelations(ctx, args as never); await rejectOverlap(ctx, args as never); const { scheduleId, ...patch } = args; await ctx.db.patch("batchSchedules", scheduleId, { ...patch, updatedAt: Date.now() }); return null; } });
export const cancel = mutation({ args: { scheduleId: v.id("batchSchedules") }, returns: v.null(), handler: async (ctx, args) => { await requireOwner(ctx); const schedule = await mustGet(ctx, "batchSchedules", args.scheduleId, "Schedule"); if (schedule.status !== "cancelled") await ctx.db.patch("batchSchedules", args.scheduleId, { status: "cancelled", updatedAt: Date.now() }); return null; } });
