import { paginationOptsValidator } from "convex/server";
import { ConvexError, v } from "convex/values";
import { mutation, query } from "../_generated/server";
import { requireOwner } from "../model/auth";
import { assertDateRange, mustGet, paginationResult, scheduleDoc } from "./shared";
import { scheduleBatchCourseSnapshot } from "./snapshotHooks";

const scheduleFields = { batchId: v.id("batches"), teacherId: v.id("teachers"), subjectId: v.optional(v.id("subjects")), weekday: v.number(), startMinutes: v.number(), endMinutes: v.number(), effectiveFrom: v.string(), effectiveUntil: v.optional(v.string()) };
const collision = v.object({ kind: v.union(v.literal("teacher"), v.literal("batch")), scheduleId: v.id("batchSchedules"), batchId: v.id("batches"), teacherId: v.id("teachers"), weekday: v.number(), startMinutes: v.number(), endMinutes: v.number(), effectiveFrom: v.string(), effectiveUntil: v.optional(v.string()) });

function validateTime(args: { weekday: number; startMinutes: number; endMinutes: number; effectiveFrom: string; effectiveUntil?: string }) { if (!Number.isSafeInteger(args.weekday) || args.weekday < 0 || args.weekday > 6) throw new Error("Weekday must be 0-6, where 0 is Sunday"); if (!Number.isSafeInteger(args.startMinutes) || !Number.isSafeInteger(args.endMinutes) || args.startMinutes < 0 || args.endMinutes > 1440 || args.endMinutes <= args.startMinutes) throw new Error("Schedule minutes must form a valid range within one day"); assertDateRange(args.effectiveFrom, args.effectiveUntil); }

async function validateRelations(ctx: Parameters<typeof mustGet>[0], args: { batchId: never; teacherId: never; subjectId?: never }) { const batch = await mustGet(ctx, "batches", args.batchId, "Batch"); const teacher = await mustGet(ctx, "teachers", args.teacherId, "Teacher"); if (batch.status === "archived" || batch.status === "completed" || teacher.status !== "active") throw new Error("Archived, completed, or inactive records cannot receive schedules"); if (args.subjectId) await mustGet(ctx, "subjects", args.subjectId, "Subject"); const assignments = await ctx.db.query("teacherBatchAssignments").withIndex("by_teacherId_and_batchId", q => q.eq("teacherId", args.teacherId).eq("batchId", args.batchId)).take(100); if (!assignments.some(a => a.status === "active" && a.subjectId === args.subjectId)) throw new Error("An active matching teacher-batch assignment is required"); }

async function findOverlaps(ctx: Parameters<typeof mustGet>[0], args: { scheduleId?: string; batchId: never; teacherId: never; weekday: number; startMinutes: number; endMinutes: number; effectiveFrom: string; effectiveUntil?: string }) { const teacherRows = await ctx.db.query("batchSchedules").withIndex("by_teacherId_and_weekday_and_status", q => q.eq("teacherId", args.teacherId).eq("weekday", args.weekday).eq("status", "active")).take(200); const batchRows = await ctx.db.query("batchSchedules").withIndex("by_batchId_and_weekday_and_status", q => q.eq("batchId", args.batchId).eq("weekday", args.weekday).eq("status", "active")).take(200); const overlaps = (row: (typeof teacherRows)[number]) => { const datesOverlap = !(args.effectiveUntil && args.effectiveUntil < row.effectiveFrom) && !(row.effectiveUntil && row.effectiveUntil < args.effectiveFrom); return row._id !== args.scheduleId && datesOverlap && args.startMinutes < row.endMinutes && args.endMinutes > row.startMinutes; }; const result = [...teacherRows.filter(overlaps).map(row => ({ kind: "teacher" as const, row })), ...batchRows.filter(overlaps).map(row => ({ kind: "batch" as const, row }))]; return result.filter((item, index) => result.findIndex(other => other.kind === item.kind && other.row._id === item.row._id) === index).map(({ kind, row }) => ({ kind, scheduleId: row._id, batchId: row.batchId, teacherId: row.teacherId, weekday: row.weekday, startMinutes: row.startMinutes, endMinutes: row.endMinutes, effectiveFrom: row.effectiveFrom, effectiveUntil: row.effectiveUntil })); }

export const previewConflicts = query({ args: { ...scheduleFields, scheduleId: v.optional(v.id("batchSchedules")) }, returns: v.array(collision), handler: async (ctx, args) => { await requireOwner(ctx); validateTime(args); return await findOverlaps(ctx, args as never); } });

export const listForBatch = query({ args: { batchId: v.id("batches"), status: v.union(v.literal("active"), v.literal("cancelled")), paginationOpts: paginationOptsValidator }, returns: paginationResult(scheduleDoc), handler: async (ctx, args) => { await requireOwner(ctx); return await ctx.db.query("batchSchedules").withIndex("by_batchId_and_status", q => q.eq("batchId", args.batchId).eq("status", args.status)).paginate(args.paginationOpts); } });
export const create = mutation({ args: scheduleFields, returns: v.id("batchSchedules"), handler: async (ctx, args) => { await requireOwner(ctx); validateTime(args); await validateRelations(ctx, args as never); const conflicts = await findOverlaps(ctx, args as never); if (conflicts.length) throw new ConvexError({ code: "SCHEDULE_CONFLICT", conflicts }); const now = Date.now(); const id = await ctx.db.insert("batchSchedules", { ...args, status: "active", createdAt: now, updatedAt: now }); await scheduleBatchCourseSnapshot(ctx, args.batchId); return id; } });
export const update = mutation({ args: { scheduleId: v.id("batchSchedules"), ...scheduleFields }, returns: v.null(), handler: async (ctx, args) => { await requireOwner(ctx); const current = await mustGet(ctx, "batchSchedules", args.scheduleId, "Schedule"); if (current.status === "cancelled") throw new Error("Cancelled schedules cannot be edited"); validateTime(args); await validateRelations(ctx, args as never); const conflicts = await findOverlaps(ctx, args as never); if (conflicts.length) throw new ConvexError({ code: "SCHEDULE_CONFLICT", conflicts }); const { scheduleId, ...patch } = args; await ctx.db.patch("batchSchedules", scheduleId, { ...patch, roomBn: undefined, roomEn: undefined, updatedAt: Date.now() }); await scheduleBatchCourseSnapshot(ctx, current.batchId); if (current.batchId !== args.batchId) await scheduleBatchCourseSnapshot(ctx, args.batchId); return null; } });
export const cancel = mutation({ args: { scheduleId: v.id("batchSchedules") }, returns: v.null(), handler: async (ctx, args) => { await requireOwner(ctx); const schedule = await mustGet(ctx, "batchSchedules", args.scheduleId, "Schedule"); if (schedule.status !== "cancelled") await ctx.db.patch("batchSchedules", args.scheduleId, { status: "cancelled", updatedAt: Date.now() }); await scheduleBatchCourseSnapshot(ctx, schedule.batchId); return null; } });
