import { paginationOptsValidator } from "convex/server";
import { v } from "convex/values";
import { mutation, query } from "../_generated/server";
import { requireOwner } from "../model/auth";
import { writeAudit } from "../model/audit";
import { cleanRequired, mustGet, normalizeCode, paginationResult, subjectDoc } from "./shared";

export const list = query({ args: { status: v.union(v.literal("active"), v.literal("archived")), paginationOpts: paginationOptsValidator }, returns: paginationResult(subjectDoc), handler: async (ctx, args) => { await requireOwner(ctx); return await ctx.db.query("subjects").withIndex("by_status", q => q.eq("status", args.status)).paginate(args.paginationOpts); } });
export const get = query({ args: { subjectId: v.id("subjects") }, returns: subjectDoc, handler: async (ctx, args) => { await requireOwner(ctx); return await mustGet(ctx, "subjects", args.subjectId, "Subject"); } });
export const create = mutation({ args: { code: v.string(), nameBn: v.string(), nameEn: v.string() }, returns: v.id("subjects"), handler: async (ctx, args) => { const { account } = await requireOwner(ctx); const code = normalizeCode(args.code); if (await ctx.db.query("subjects").withIndex("by_code", q => q.eq("code", code)).unique()) throw new Error("Subject code already exists"); const now = Date.now(); const id = await ctx.db.insert("subjects", { code, nameBn: cleanRequired(args.nameBn, "Bangla name"), nameEn: cleanRequired(args.nameEn, "English name"), status: "active", createdAt: now, updatedAt: now }); await writeAudit(ctx, { actorAccountId: account._id, actorRole: "owner", action: "subject.created", entityType: "subject", entityId: id, summary: "Subject created" }); return id; } });
export const update = mutation({ args: { subjectId: v.id("subjects"), code: v.string(), nameBn: v.string(), nameEn: v.string() }, returns: v.null(), handler: async (ctx, args) => { await requireOwner(ctx); const current = await mustGet(ctx, "subjects", args.subjectId, "Subject"); if (current.status === "archived") throw new Error("Archived subjects cannot be edited"); const code = normalizeCode(args.code); const duplicate = await ctx.db.query("subjects").withIndex("by_code", q => q.eq("code", code)).unique(); if (duplicate && duplicate._id !== args.subjectId) throw new Error("Subject code already exists"); await ctx.db.patch("subjects", args.subjectId, { code, nameBn: cleanRequired(args.nameBn, "Bangla name"), nameEn: cleanRequired(args.nameEn, "English name"), updatedAt: Date.now() }); return null; } });
export const archive = mutation({ args: { subjectId: v.id("subjects") }, returns: v.null(), handler: async (ctx, args) => { const { account } = await requireOwner(ctx); const current = await mustGet(ctx, "subjects", args.subjectId, "Subject"); if (current.status === "archived") return null; const links = await ctx.db.query("courseSubjects").withIndex("by_subjectId", q => q.eq("subjectId", args.subjectId)).take(1); if (links.length) throw new Error("Subject linked to a course cannot be archived"); await ctx.db.patch("subjects", args.subjectId, { status: "archived", updatedAt: Date.now() }); await writeAudit(ctx, { actorAccountId: account._id, actorRole: "owner", action: "subject.archived", entityType: "subject", entityId: args.subjectId, summary: "Subject archived" }); return null; } });
