"use client";

import { useMutation, useQuery } from "convex/react";
import { useState, type FormEvent } from "react";
import { api } from "@convex/_generated/api";
import { PortalPageState } from "./PortalPageState";
import { WebsiteCmsEditor } from "./WebsiteCmsEditor";

const keys = ["hero", "about_summary", "contact", "achievement_intro", "admission_intro", "footer"] as const;

function Feedback({ value }: { value: { ok: boolean; text: string } | null }) { return value ? <p className={`form-message ${value.ok ? "success" : "error"}`} role={value.ok ? "status" : "alert"}>{value.text}</p> : null; }

export function OwnerSettingsEditor({ locale }: { locale: "bn" | "en" }) {
  const data = useQuery(api.settings.getOwner, {}); const update = useMutation(api.settings.updateOperations); const seed = useMutation(api.messaging.templateFunctions.seedDefaults);
  const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState<{ ok: boolean; text: string } | null>(null); const bn = locale === "bn";
  if (data === undefined) return <PortalPageState state="loading" locale={locale} />;
  if (data === null) return <PortalPageState state="empty" locale={locale} emptyTitle={bn ? "কোচিং সেটিংস এখনো শুরু করা হয়নি" : "Coaching settings are not initialized"} />;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); setBusy(true); setFeedback(null); try { await update({ monthlyDueDay: Number(values.get("monthlyDueDay")), defaultLocale: values.get("defaultLocale") === "en" ? "en" : "bn", defaultGuardianSmsLocale: values.get("defaultGuardianSmsLocale") === "en" ? "en" : "bn", publicAdmissionsOpen: values.get("publicAdmissionsOpen") === "on", smsEnabled: values.get("smsEnabled") === "on", receiptFooterBn: String(values.get("receiptFooterBn") || ""), receiptFooterEn: String(values.get("receiptFooterEn") || "") }); setFeedback({ ok: true, text: bn ? "সেটিংস সংরক্ষিত হয়েছে।" : "Settings saved." }); } catch (cause) { setFeedback({ ok: false, text: cause instanceof Error ? cause.message : "Could not save settings" }); } finally { setBusy(false); } }
  return <><header className="portal-page-header"><p className="eyebrow">{bn ? "অপারেশন" : "Operations"}</p><h1>{bn ? "সেটিংস" : "Settings"}</h1><p>{bn ? "ভর্তি, মাসিক বকেয়া, SMS এবং রশিদের ডিফল্ট নিয়ন্ত্রণ করুন।" : "Control admission, monthly dues, SMS, and receipt defaults."}</p></header><form className="operation-form" key={data.updatedAt} onSubmit={submit}><fieldset><legend>{bn ? "ডিফল্ট" : "Defaults"}</legend><div className="form-grid"><label>{bn ? "মাসিক বকেয়ার দিন" : "Monthly due day"}<input name="monthlyDueDay" type="number" min={1} max={28} defaultValue={data.monthlyDueDay} required /></label><label>{bn ? "ইন্টারফেস ভাষা" : "Interface locale"}<select name="defaultLocale" defaultValue={data.defaultLocale}><option value="bn">বাংলা</option><option value="en">English</option></select></label><label>{bn ? "অভিভাবক SMS ভাষা" : "Guardian SMS locale"}<select name="defaultGuardianSmsLocale" defaultValue={data.defaultGuardianSmsLocale}><option value="bn">বাংলা</option><option value="en">English</option></select></label></div></fieldset><fieldset><legend>{bn ? "সুবিধা" : "Features"}</legend><label className="check-row"><input name="publicAdmissionsOpen" type="checkbox" defaultChecked={data.publicAdmissionsOpen} /><span>{bn ? "পাবলিক ভর্তি আবেদন চালু" : "Public admissions open"}</span></label><label className="check-row"><input name="smsEnabled" type="checkbox" defaultChecked={data.smsEnabled} /><span>{bn ? "SMS ডেলিভারি চালু" : "SMS delivery enabled"}</span></label></fieldset><fieldset><legend>{bn ? "রশিদের ফুটার" : "Receipt footer"}</legend><div className="form-grid"><label>বাংলা<textarea name="receiptFooterBn" defaultValue={data.receiptFooterBn} rows={3} /></label><label>English<textarea name="receiptFooterEn" defaultValue={data.receiptFooterEn} rows={3} /></label></div></fieldset><Feedback value={feedback} /><div className="form-actions"><button className="button button-primary" disabled={busy}>{bn ? "সংরক্ষণ করুন" : "Save settings"}</button><button className="button button-secondary" type="button" onClick={async () => { setBusy(true); try { const count = await seed({}); setFeedback({ ok: true, text: `${count} ${bn ? "টি SMS টেমপ্লেট যোগ হয়েছে।" : "SMS templates added."}` }); } catch (cause) { setFeedback({ ok: false, text: cause instanceof Error ? cause.message : "Could not seed templates" }); } finally { setBusy(false); } }}>{bn ? "ডিফল্ট SMS টেমপ্লেট তৈরি" : "Seed SMS templates"}</button></div></form></>;
}

export function LegacyOwnerWebsiteEditor({ locale }: { locale: "bn" | "en" }) {
  const [key, setKey] = useState<(typeof keys)[number]>("hero"); const preview = useQuery(api.publicSite.cms.getContentPreview, { key }); const save = useMutation(api.publicSite.cms.saveContentDraft); const publish = useMutation(api.publicSite.cms.publishContent);
  const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState<{ ok: boolean; text: string } | null>(null); const bn = locale === "bn";
  if (preview === undefined) return <PortalPageState state="loading" locale={locale} />;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setFeedback(null); try { await save({ key, content: { titleBn: String(data.get("titleBn") || ""), titleEn: String(data.get("titleEn") || ""), bodyBn: String(data.get("bodyBn") || ""), bodyEn: String(data.get("bodyEn") || ""), primaryCtaLabelBn: String(data.get("primaryCtaLabelBn") || "") || null, primaryCtaLabelEn: String(data.get("primaryCtaLabelEn") || "") || null, primaryCtaHref: String(data.get("primaryCtaHref") || "") || null, mediaStorageId: preview?.mediaStorageId ?? null } }); setFeedback({ ok: true, text: bn ? "খসড়া সংরক্ষিত হয়েছে। প্রকাশ না করা পর্যন্ত এটি পাবলিক হবে না।" : "Draft saved. It remains private until published." }); } catch (cause) { setFeedback({ ok: false, text: cause instanceof Error ? cause.message : "Could not save draft" }); } finally { setBusy(false); } }
  return <><header className="portal-page-header"><p className="eyebrow">CMS</p><h1>{bn ? "পাবলিক ওয়েবসাইট" : "Public website"}</h1><p>{bn ? "নির্ধারিত দ্বিভাষিক কনটেন্ট স্লট সম্পাদনা, প্রিভিউ এবং প্রকাশ করুন।" : "Edit, preview, and publish fixed bilingual content slots."}</p></header><label className="standalone-field">{bn ? "কনটেন্ট অংশ" : "Content section"}<select value={key} onChange={(event) => { setKey(event.target.value as (typeof keys)[number]); setFeedback(null); }}>{keys.map((value) => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><form className="operation-form" key={`${key}:${preview?.updatedAt ?? 0}`} onSubmit={submit}><fieldset><legend>{bn ? "শিরোনাম" : "Titles"}</legend><div className="form-grid"><label>বাংলা<input name="titleBn" defaultValue={preview?.titleBn} /></label><label>English<input name="titleEn" defaultValue={preview?.titleEn} /></label></div></fieldset><fieldset><legend>{bn ? "মূল লেখা" : "Body"}</legend><div className="form-grid"><label>বাংলা<textarea name="bodyBn" rows={8} defaultValue={preview?.bodyBn} /></label><label>English<textarea name="bodyEn" rows={8} defaultValue={preview?.bodyEn} /></label></div></fieldset><fieldset><legend>CTA</legend><div className="form-grid"><label>বাংলা<input name="primaryCtaLabelBn" defaultValue={preview?.primaryCtaLabelBn ?? ""} /></label><label>English<input name="primaryCtaLabelEn" defaultValue={preview?.primaryCtaLabelEn ?? ""} /></label><label>URL<input name="primaryCtaHref" defaultValue={preview?.primaryCtaHref ?? ""} placeholder="/bn/admission" /></label></div></fieldset>{preview && <p className="editor-meta">{bn ? "সর্বশেষ সম্পাদনা" : "Last edited"}: {new Date(preview.updatedAt).toLocaleString()} · {bn ? "খসড়া" : "Draft"} v{preview.draftRevision} · {bn ? "প্রকাশিত" : "Published"} v{preview.publishedRevision}</p>}<Feedback value={feedback} /><div className="form-actions"><button className="button button-secondary" disabled={busy}>{bn ? "খসড়া সংরক্ষণ" : "Save draft"}</button><button className="button button-primary" type="button" disabled={busy || !preview} onClick={async () => { setBusy(true); try { await publish({ key }); setFeedback({ ok: true, text: bn ? "কনটেন্ট প্রকাশিত হয়েছে।" : "Content published." }); } catch (cause) { setFeedback({ ok: false, text: cause instanceof Error ? cause.message : "Could not publish" }); } finally { setBusy(false); } }}>{bn ? "প্রকাশ করুন" : "Publish"}</button></div></form></>;
}

export { WebsiteCmsEditor as OwnerWebsiteEditor };
