"use client";

import { useQuery } from "convex/react";
import { api } from "@convex/_generated/api";
import type { Id } from "@convex/_generated/dataModel";
import { PortalPageState } from "./PortalPageState";

export function ReceiptPrint({ locale, paymentId }: { locale: "bn" | "en"; paymentId: string }) {
  const receipt = useQuery(api.finance.functions.getReceipt, { paymentId: paymentId as Id<"payments"> }); const bn = locale === "bn";
  if (receipt === undefined) return <PortalPageState state="loading" locale={locale} />;
  if (receipt === null) return <PortalPageState state="empty" locale={locale} emptyTitle={bn ? "রশিদ পাওয়া যায়নি" : "Receipt not found"} />;
  const amount = (value: number) => new Intl.NumberFormat(bn ? "bn-BD" : "en-BD", { style: "currency", currency: "BDT" }).format(value / 100);
  return <div className="receipt-sheet"><div className="receipt-toolbar" data-print-hidden><button className="button button-primary" onClick={() => window.print()}>{bn ? "প্রিন্ট করুন" : "Print receipt"}</button></div><header className="receipt-head"><div><p className="eyebrow">{bn ? "পেমেন্ট রশিদ" : "Payment receipt"}</p><h1>{bn ? receipt.coachingNameBn : receipt.coachingNameEn}</h1><p>{bn ? receipt.addressBn : receipt.addressEn} · +{receipt.phone}</p></div><div><strong>{receipt.receiptNumber}</strong><span>{new Intl.DateTimeFormat(bn ? "bn-BD" : "en-GB", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Dhaka" }).format(receipt.paidAt)}</span></div></header><dl className="receipt-meta"><div><dt>{bn ? "শিক্ষার্থী" : "Student"}</dt><dd>{receipt.studentName} ({receipt.studentNumber})</dd></div><div><dt>{bn ? "অভিভাবক" : "Guardian"}</dt><dd>{receipt.guardianName}</dd></div><div><dt>{bn ? "পদ্ধতি" : "Method"}</dt><dd>{receipt.method}</dd></div><div><dt>{bn ? "অবস্থা" : "Status"}</dt><dd>{receipt.status}</dd></div></dl><table className="receipt-lines"><thead><tr><th>{bn ? "বিবরণ" : "Description"}</th><th>{bn ? "পরিমাণ" : "Amount"}</th></tr></thead><tbody>{receipt.allocations.map((line, index) => <tr key={`${line.descriptionEn}:${index}`}><td>{bn ? line.descriptionBn : line.descriptionEn}{line.reversed ? ` (${bn ? "বাতিল" : "reversed"})` : ""}</td><td>{amount(line.amountMinor)}</td></tr>)}{receipt.advanceAmountMinor > 0 && <tr><td>{bn ? "অগ্রিম জমা" : "Advance credit"}</td><td>{amount(receipt.advanceAmountMinor)}</td></tr>}</tbody><tfoot><tr><th>{bn ? "মোট পরিশোধ" : "Total paid"}</th><th>{amount(receipt.amountMinor)}</th></tr></tfoot></table><footer className="receipt-footer"><p>{bn ? receipt.footerBn : receipt.footerEn}</p><small>{bn ? "এই রশিদটি সিস্টেম থেকে তৈরি।" : "This receipt was generated by the system."}</small></footer></div>;
}
