"use client";

import { api } from "@convex/_generated/api";
import type { Id } from "@convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { useQuery } from "convex/react";
import { Printer } from "lucide-react";
import { PortalPageState } from "./PortalPageState";

const amount = (minor: number) =>
  new Intl.NumberFormat("en-BD", { style: "currency", currency: "BDT" }).format(
    minor / 100,
  );

export function ReceiptPrint({
  locale,
  collectionId,
}: {
  locale: "bn" | "en";
  collectionId: string;
}) {
  const receipt = useQuery(api.fees.functions.getReceipt, {
    collectionId: collectionId as Id<"feeCollections">,
  });
  if (receipt === undefined)
    return <PortalPageState state="loading" locale={locale} />;
  if (receipt === null)
    return (
      <PortalPageState
        state="empty"
        locale={locale}
        emptyTitle={
          locale === "bn" ? "রশিদ পাওয়া যায়নি" : "Receipt not found"
        }
      />
    );
  return (
    <div className="receipt-sheet">
      <div className="receipt-toolbar" data-print-hidden>
        <Button onClick={() => window.print()}>
          <Printer data-icon="inline-start" />
          Print / Save PDF
        </Button>
      </div>
      {receipt.status === "voided" ? (
        <div className="receipt-voided">VOIDED</div>
      ) : null}
      <header className="receipt-head">
        <div>
          <p className="eyebrow">CASH RECEIPT</p>
          <h1>{receipt.coachingName}</h1>
          <p>
            {receipt.address} · {receipt.phone}
          </p>
        </div>
        <div>
          <strong>{receipt.receiptNumber}</strong>
          <span>{receipt.collectedOn}</span>
        </div>
      </header>
      <dl className="receipt-meta">
        <div>
          <dt>Student</dt>
          <dd>
            {receipt.studentName} ({receipt.studentNumber})
          </dd>
        </div>
        <div>
          <dt>Course</dt>
          <dd>{receipt.courseName}</dd>
        </div>
        <div>
          <dt>Batch</dt>
          <dd>{receipt.batchName}</dd>
        </div>
        <div>
          <dt>Collected by</dt>
          <dd>{receipt.collectedBy}</dd>
        </div>
      </dl>
      <table className="receipt-lines">
        <thead>
          <tr>
            <th>Description</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          {receipt.items.map((item, index) => (
            <tr key={`${item.description}:${index}`}>
              <td>
                {item.description}
                {item.reversed ? " (reversed)" : ""}
              </td>
              <td>{amount(item.amountMinor)}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr>
            <th>Total cash received</th>
            <th>{amount(receipt.amountMinor)}</th>
          </tr>
        </tfoot>
      </table>
      {receipt.note ? (
        <p>
          <strong>Note:</strong> {receipt.note}
        </p>
      ) : null}
      {receipt.voidReason ? (
        <p>
          <strong>Void reason:</strong> {receipt.voidReason}
        </p>
      ) : null}
      <footer className="receipt-footer">
        <p>{receipt.footer}</p>
        <div className="receipt-signature">Authorized signature</div>
        <small>This receipt was generated by the system.</small>
      </footer>
    </div>
  );
}
