"use client";

import { useMutation, useQuery } from "convex/react";
import { useState, type FormEvent } from "react";
import { api } from "@convex/_generated/api";
import { PortalPageState } from "./PortalPageState";

type RoutineRow = { scheduleId: string; batchNameBn: string; batchNameEn: string; teacherName: string; weekday: number; startMinutes: number; endMinutes: number };
const weekdaysBn = ["রবি", "সোম", "মঙ্গল", "বুধ", "বৃহস্পতি", "শুক্র", "শনি"];
const weekdaysEn = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const clock = (minutes: number) => `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`;

function RoutineTable({ locale, rows }: { locale: "bn" | "en"; rows: RoutineRow[] }) { const bn = locale === "bn"; return <><header className="portal-page-header"><p className="eyebrow">{bn ? "সাপ্তাহিক" : "Weekly"}</p><h1>{bn ? "ক্লাস রুটিন" : "Class routine"}</h1></header>{rows.length ? <div className="table-wrap"><table><thead><tr><th>{bn ? "দিন" : "Day"}</th><th>{bn ? "ব্যাচ" : "Batch"}</th><th>{bn ? "সময়" : "Time"}</th><th>{bn ? "শিক্ষক" : "Teacher"}</th></tr></thead><tbody>{[...rows].sort((a, b) => a.weekday - b.weekday || a.startMinutes - b.startMinutes).map((row) => <tr key={row.scheduleId}><td>{(bn ? weekdaysBn : weekdaysEn)[row.weekday]}</td><td>{bn ? row.batchNameBn : row.batchNameEn}</td><td>{clock(row.startMinutes)}–{clock(row.endMinutes)}</td><td>{row.teacherName}</td></tr>)}</tbody></table></div> : <p className="empty-panel">{bn ? "কোনো সক্রিয় রুটিন নেই।" : "No active routine."}</p>}</>; }

export function TeacherRoutine({ locale }: { locale: "bn" | "en" }) { const rows = useQuery(api.academics.readModels.teacherRoutine, {}); return rows ? <RoutineTable locale={locale} rows={rows} /> : <PortalPageState state="loading" locale={locale} />; }
export function StudentRoutine({ locale }: { locale: "bn" | "en" }) { const rows = useQuery(api.academics.readModels.studentRoutine, {}); return rows ? <RoutineTable locale={locale} rows={rows} /> : <PortalPageState state="loading" locale={locale} />; }

export function TeacherProfile({ locale }: { locale: "bn" | "en" }) { const profile = useQuery(api.academics.readModels.teacherProfile, {}); const bn = locale === "bn"; if (!profile) return <PortalPageState state="loading" locale={locale} />; return <><header className="portal-page-header"><p className="eyebrow">{profile.employeeCode}</p><h1>{profile.displayName}</h1></header><dl className="detail-list"><div><dt>{bn ? "Google ইমেইল" : "Google email"}</dt><dd>{profile.loginEmail}</dd></div><div><dt>{bn ? "ফোন" : "Phone"}</dt><dd>{profile.phone}</dd></div><div><dt>{bn ? "যোগ্যতা" : "Qualifications"}</dt><dd>{bn ? profile.qualificationsBn : profile.qualificationsEn}</dd></div><div><dt>{bn ? "অবস্থা" : "Status"}</dt><dd>{profile.status}</dd></div></dl><div className="prose-copy">{bn ? profile.bioBn : profile.bioEn}</div></>; }

export function StudentProfile({ locale }: { locale: "bn" | "en" }) {
  const profile = useQuery(api.students.self.getMyProfile, {}); const update = useMutation(api.students.self.updateMyProfile); const request = useMutation(api.students.self.requestSensitiveChange); const bn = locale === "bn"; const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null);
  if (!profile) return <PortalPageState state="loading" locale={locale} />;
  async function execute(work: () => Promise<unknown>) { setBusy(true); setMessage(null); try { await work(); setMessage(bn ? "প্রোফাইল অনুরোধ সংরক্ষিত হয়েছে।" : "Profile request saved."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Update failed"); } finally { setBusy(false); } }
  function submitDirect(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void execute(() => update({ phone: String(data.get("phone") || "") || null, schoolCollege: String(data.get("schoolCollege")), currentClass: String(data.get("currentClass")), address: String(data.get("address") || "") || null, preferredSmsLocale: data.get("preferredSmsLocale") === "en" ? "en" : "bn" })); }
  function submitSensitive(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); void execute(() => request({ fieldKey: data.get("fieldKey") as "displayName" | "loginEmail" | "guardianName" | "guardianPhone" | "guardianRelationship" | "alternateGuardianPhone", requestedValue: String(data.get("requestedValue")), reason: String(data.get("reason") || "") || undefined })); }
  return <><header className="portal-page-header"><p className="eyebrow">{profile.studentNumber}</p><h1>{profile.displayName}</h1><p>{bn ? "অনুমোদিত ক্ষেত্র সরাসরি সম্পাদনা করুন; সংবেদনশীল তথ্য মালিকের অনুমোদন চায়।" : "Edit permitted fields directly; sensitive information requires owner approval."}</p></header>{message && <p className="form-message success">{message}</p>}<div className="editor-grid"><form className="operation-form compact-form" key={profile.studentId} onSubmit={submitDirect}><fieldset><legend>{bn ? "সরাসরি সম্পাদনা" : "Directly editable"}</legend><label>{bn ? "ফোন" : "Phone"}<input name="phone" defaultValue={profile.phone ?? ""} /></label><label>{bn ? "স্কুল/কলেজ" : "School/college"}<input name="schoolCollege" defaultValue={profile.schoolCollege} required /></label><label>{bn ? "বর্তমান শ্রেণি" : "Current class"}<input name="currentClass" defaultValue={profile.currentClass} required /></label><label>{bn ? "ঠিকানা" : "Address"}<textarea name="address" defaultValue={profile.address ?? ""} rows={4} /></label><label>{bn ? "SMS ভাষা" : "SMS locale"}<select name="preferredSmsLocale" defaultValue={profile.preferredSmsLocale}><option value="bn">বাংলা</option><option value="en">English</option></select></label><button className="button button-primary" disabled={busy}>{bn ? "সংরক্ষণ" : "Save"}</button></fieldset></form><form className="operation-form compact-form" onSubmit={submitSensitive}><fieldset><legend>{bn ? "পরিবর্তনের অনুরোধ" : "Request a sensitive change"}</legend><label>{bn ? "ক্ষেত্র" : "Field"}<select name="fieldKey"><option value="displayName">{bn ? "অফিসিয়াল নাম" : "Official name"}</option><option value="loginEmail">Google email</option><option value="guardianName">{bn ? "অভিভাবকের নাম" : "Guardian name"}</option><option value="guardianPhone">{bn ? "অভিভাবকের ফোন" : "Guardian phone"}</option><option value="guardianRelationship">{bn ? "সম্পর্ক" : "Relationship"}</option><option value="alternateGuardianPhone">{bn ? "বিকল্প ফোন" : "Alternate phone"}</option></select></label><label>{bn ? "নতুন মান" : "Requested value"}<input name="requestedValue" required /></label><label>{bn ? "কারণ" : "Reason"}<textarea name="reason" rows={4} /></label><button className="button button-secondary" disabled={busy}>{bn ? "অনুরোধ পাঠান" : "Send request"}</button>{profile.pendingChanges.length > 0 && <p>{profile.pendingChanges.length} {bn ? "টি অনুরোধ অপেক্ষমাণ" : "requests pending"}</p>}</fieldset></form></div></>;
}
