import { Button, PageHeader, Status } from "./portal-shell";

const students = [
  ["ST-1024", "Rahim Ahmed", "Abdul Karim", "HSC Science A", "৳1,200", "Active", "87%"],
  ["ST-1025", "Nusrat Jahan", "Farida Begum", "SSC English B", "৳0", "Active", "94%"],
  ["ST-1026", "Fahim Hasan", "Mizanur Rahman", "HSC Science A", "৳2,400", "Active", "76%"],
  ["ST-1027", "Sadia Islam", "Rokeya Islam", "Admission Math", "৳0", "Active", "91%"],
  ["ST-1028", "Tanvir Hossain", "Shah Alam", "SSC English B", "৳800", "Inactive", "68%"],
];

function Stat({ label, value, detail, tone }: { label: string; value: string; detail: string; tone: string }) {
  return <div className={`stat-card stat-${tone}`}><div className="stat-top"><span>{label}</span><span className="stat-symbol">{tone === "blue" ? "↗" : tone === "green" ? "✓" : tone === "orange" ? "৳" : "!"}</span></div><strong>{value}</strong><small>{detail}</small></div>;
}

export function DashboardPage() {
  return <>
    <PageHeader eyebrow="Friday, 10 July 2026" title="Good morning, Sayed" description="Here’s what needs your attention today." action={<Button>＋ Add student</Button>} />
    <div className="quick-actions"><Button>＋ Add student</Button><Button secondary>৳ Collect payment</Button><Button secondary>✓ Take attendance</Button><Button secondary>▤ Enter results</Button></div>
    <div className="stat-grid"><Stat label="Active students" value="428" detail="↑ 12 this month" tone="blue" /><Stat label="Today’s collection" value="৳18,450" detail="24 payments received" tone="green" /><Stat label="Outstanding dues" value="৳42,300" detail="36 students overdue" tone="orange" /><Stat label="Attendance pending" value="3 batches" detail="Needs action today" tone="red" /></div>
    <div className="content-grid dashboard-grid">
      <section className="panel"><div className="panel-heading"><div><h2>Today’s classes</h2><p>Friday, 10 July · 6 classes scheduled</p></div><a href="#">View routine →</a></div><div className="class-list"><ClassRow time="09:00" batch="HSC Science · Batch A" detail="Physics · Room 204" count="32 students" state="Attendance pending" /><ClassRow time="11:30" batch="SSC English · Batch B" detail="English 2nd paper · Room 103" count="28 students" state="Attendance done" done /><ClassRow time="16:00" batch="Admission Math" detail="Mathematics · Room 301" count="24 students" state="Upcoming" /></div></section>
      <section className="panel attention-panel"><div className="panel-heading"><div><h2>Needs attention</h2><p>Small things worth handling now</p></div><span className="count-badge">4</span></div><div className="attention-list"><Attention icon="৳" title="Overdue payments" detail="36 students · ৳42,300 outstanding" tone="orange" /><Attention icon="✓" title="Attendance not recorded" detail="3 batches from today" tone="red" /><Attention icon="▤" title="Results awaiting review" detail="HSC monthly test" tone="blue" /><Attention icon="◌" title="SMS delivery failed" detail="3 messages need retry" tone="purple" /></div></section>
    </div>
    <section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>The latest changes across your centre</p></div><a href="#">View all →</a></div><div className="activity-list"><Activity icon="৳" title="Payment received from Rahim Ahmed" detail="Monthly tuition · ৳2,000" time="8 min ago" tone="green" /><Activity icon="＋" title="New student admitted" detail="Sadia Islam joined Admission Math" time="32 min ago" tone="blue" /><Activity icon="▤" title="Result published" detail="SSC English · Monthly test" time="1 hr ago" tone="purple" /></div></section>
  </>;
}

function ClassRow({ time, batch, detail, count, state, done }: { time: string; batch: string; detail: string; count: string; state: string; done?: boolean }) {
  return <div className="class-row"><time>{time}</time><div className="class-info"><strong>{batch}</strong><span>{detail}</span></div><span className="class-count">{count}</span><Status tone={done ? "green" : state === "Upcoming" ? "gray" : "orange"}>{state}</Status>{done ? <button className="row-link">View</button> : <button className="row-link primary-link">Open →</button>}</div>;
}

function Attention({ icon, title, detail, tone }: { icon: string; title: string; detail: string; tone: string }) { return <div className="attention-row"><span className={`attention-icon ${tone}`}>{icon}</span><div><strong>{title}</strong><span>{detail}</span></div><span className="arrow">→</span></div>; }
function Activity({ icon, title, detail, time, tone }: { icon: string; title: string; detail: string; time: string; tone: string }) { return <div className="activity-row"><span className={`activity-icon ${tone}`}>{icon}</span><div><strong>{title}</strong><span>{detail}</span></div><time>{time}</time></div>; }

export function StudentsPage() {
  return <><PageHeader eyebrow="Workspace / Students" title="Students" description="Manage admissions, enrolments, guardians, and student history." action={<Button>＋ Add student</Button>} /><div className="toolbar"><div className="table-search">⌕ <input placeholder="Search name, ID, phone, guardian..." /></div><button className="filter-button">Batch <span>⌄</span></button><button className="filter-button">Status <span>⌄</span></button><button className="filter-button">More filters <span>⌄</span></button><span className="toolbar-spacer" /><button className="view-button active">☷</button><button className="view-button">▦</button></div><div className="table-meta"><span><strong>428</strong> active students</span><span>Last updated just now</span></div><section className="panel table-panel"><table><thead><tr><th>Student</th><th>Guardian</th><th>Current batch</th><th>Attendance</th><th>Current due</th><th>Status</th><th /></tr></thead><tbody>{students.map(([id, name, guardian, batch, due, status, attendance]) => <tr key={id}><td><div className="student-cell"><div className="student-avatar">{name.split(" ").map((n) => n[0]).join("")}</div><div><strong>{name}</strong><span>{id}</span></div></div></td><td><span className="muted-cell">{guardian}</span><span className="sub-cell">01712 345 678</span></td><td>{batch}</td><td><span className="attendance-value">{attendance}</span></td><td className={due !== "৳0" ? "due-value" : "paid-value"}>{due}</td><td><Status tone={status === "Active" ? "green" : "gray"}>{status}</Status></td><td><button className="more-button">•••</button></td></tr>)}</tbody></table><div className="pagination"><span>Showing 1–5 of 428 students</span><div><button>‹</button><button className="current">1</button><button>2</button><button>3</button><button>›</button></div></div></section></>;
}

export function AttendancePage() {
  const roster = [["ST-1024", "Rahim Ahmed", true], ["ST-1025", "Nusrat Jahan", true], ["ST-1026", "Fahim Hasan", false], ["ST-1029", "Moumita Das", true], ["ST-1030", "Arif Hossain", true], ["ST-1031", "Jannat Ara", false]] as const;
  return <><PageHeader eyebrow="Workspace / Attendance" title="Attendance" description="Record attendance by batch and class session." action={<Button>＋ Add class session</Button>} /><div className="attendance-controls panel"><div><label>Class date</label><button className="select-control">10 July 2026 <span>⌄</span></button></div><div><label>Batch</label><button className="select-control wide">HSC Science · Batch A <span>⌄</span></button></div><div className="session-meta"><span className="session-dot" />09:00 · Physics · Room 204</div><Button>Load attendance</Button></div><section className="attendance-card panel"><div className="attendance-heading"><div><div className="eyebrow">HSC Science · Batch A</div><h2>Mark today’s attendance</h2><p>Friday, 10 July 2026 · Physics · 32 enrolled students</p></div><div className="attendance-summary"><strong>29 <small>/ 32</small></strong><span>present today</span></div></div><div className="attendance-actions"><Button secondary>✓ Mark all present</Button><span>2 absent · 1 not marked</span><button className="save-button">Save attendance</button></div><div className="roster-list">{roster.map(([id, name, present]) => <div className="roster-row" key={id}><div className={`check-circle ${present ? "checked" : ""}`}>{present ? "✓" : ""}</div><div className="roster-avatar">{String(name).split(" ").map((n) => n[0]).join("")}</div><div><strong>{name}</strong><span>{id}</span></div><button className={`attendance-state ${present ? "present" : "absent"}`}>{present ? "Present" : "Absent"}</button><button className="more-button">•••</button></div>)}</div></section></>;
}

export function PaymentsPage() {
  return <><PageHeader eyebrow="Workspace / Fees & payments" title="Fees & payments" description="Track dues, collect manual payments, and keep guardians informed." action={<Button>＋ Collect payment</Button>} /><div className="stat-grid finance-stats"><Stat label="Collected this month" value="৳128,500" detail="↑ 8.4% vs last month" tone="green" /><Stat label="Outstanding dues" value="৳42,300" detail="36 students overdue" tone="orange" /><Stat label="Collection rate" value="86.2%" detail="Across all active dues" tone="blue" /><Stat label="Payments today" value="24" detail="৳18,450 collected" tone="purple" /></div><div className="tabs"><button className="tab active">Fee dues <span>36</span></button><button className="tab">Payment history</button><button className="tab">Receipts</button></div><div className="toolbar"><div className="table-search">⌕ <input placeholder="Search student or invoice..." /></div><button className="filter-button">All statuses <span>⌄</span></button><button className="filter-button">This month <span>⌄</span></button><span className="toolbar-spacer" /><Button secondary>Send due reminders</Button></div><section className="panel table-panel"><table><thead><tr><th>Student</th><th>Description</th><th>Amount</th><th>Due date</th><th>Status</th><th /></tr></thead><tbody>{[["Rahim Ahmed", "July tuition · HSC Science A", "৳2,000", "05 Jul 2026", "Overdue", "red"], ["Fahim Hasan", "July tuition · HSC Science A", "৳2,400", "05 Jul 2026", "Overdue", "red"], ["Tanvir Hossain", "July tuition · SSC English B", "৳800", "10 Jul 2026", "Due today", "orange"], ["Maliha Chowdhury", "July tuition · Admission Math", "৳1,500", "15 Jul 2026", "Upcoming", "blue"]].map(([name, description, amount, date, status, tone]) => <tr key={name}><td><div className="student-cell"><div className="student-avatar">{name.split(" ").map((n) => n[0]).join("")}</div><strong>{name}</strong></div></td><td>{description}</td><td><strong>{amount}</strong></td><td className="muted-cell">{date}</td><td><Status tone={tone as "red" | "orange" | "blue"}>{status}</Status></td><td><button className="collect-link">Collect →</button></td></tr>)}</tbody></table></section></>;
}
